DECLARE @Asia INT = 0;
DECLARE @CentralAmerica INT = 1;
DECLARE @EasternAfrica INT = 2;
DECLARE @Europe INT = 3;
DECLARE @EuropeanUnion INT = 4;
DECLARE @MiddleAfrica INT = 5;
DECLARE @MiddleEast INT = 6;
DECLARE @NorthernAmerica INT = 7;
DECLARE @NorthernAfrica INT = 8;
DECLARE @Oceania INT = 9;
DECLARE @SouthAmerica INT = 10;
DECLARE @SouthernAfrica INT = 11;
DECLARE @TheCaribbean INT = 12;
DECLARE @WesternAfrica INT = 13;
DECLARE @CreatedBy INT = 1;

INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Afghanistan','93','AF/AFG',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Albania','355','AL/ALB',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Algeria','213','DZ/DZA',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('American Samoa','1-684','AS/ASM',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Andorra','376','AD/AND',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Angola','244','AO/AGO',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Anguilla','1-264','AI/AIA',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Antarctica','672','AQ/ATA',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Antigua and Barbuda','1-268','AG/ATG',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Argentina','54','AR/ARG',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Armenia','374','AM/ARM',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Aruba','297','AW/ABW',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Australia','61','AU/AUS',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Austria','43','AT/AUT',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Azerbaijan','994','AZ/AZE',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bahamas','1-242','BS/BHS',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bahrain','973','BH/BHR',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bangladesh','880','BD/BGD',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Barbados','1-246','BB/BRB',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Belarus','375','BY/BLR',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Belgium','32','BE/BEL',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Belize','501','BZ/BLZ',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Benin','229','BJ/BEN',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bermuda','1-441','BM/BMU',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bhutan','975','BT/BTN',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bolivia','591','BO/BOL',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bosnia and Herzegovina','387','BA/BIH',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Botswana','267','BW/BWA',@SouthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Brazil','55','BR/BRA',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('British Indian Ocean Territory','246','IO/IOT',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('British Virgin Islands','1-284','VG/VGB',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Brunei','673','BN/BRN',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Bulgaria','359','BG/BGR',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Burkina Faso','226','BF/BFA',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Burundi','257','BI/BDI',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cambodia','855','KH/KHM',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cameroon','237','CM/CMR',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Canada','1','CA/CAN',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cape Verde','238','CV/CPV',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cayman Islands','1-345','KY/CYM',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Central African Republic','236','CF/CAF',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Chad','235','TD/TCD',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Chile','56','CL/CHL',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('China','86','CN/CHN',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Christmas Island','61','CX/CXR',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cocos Islands','61','CC/CCK',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Colombia','57','CO/COL',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Comoros','269','KM/COM',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cook Islands','682','CK/COK',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Costa Rica','506','CR/CRI',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Croatia','385','HR/HRV',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cuba','53','CU/CUB',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Curacao','599','CW/CUW',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Cyprus','357','CY/CYP',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Czech Republic','420','CZ/CZE',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Democratic Republic of the Congo','243','CD/COD',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Denmark','45','DK/DNK',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Djibouti','253','DJ/DJI',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Dominica','1-767','DM/DMA',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Dominican Republic','1-809, 1-829, 1-849','DO/DOM',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('East Timor','670','TL/TLS',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Ecuador','593','EC/ECU',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Egypt','20','EG/EGY',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('El Salvador','503','SV/SLV',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Equatorial Guinea','240','GQ/GNQ',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Eritrea','291','ER/ERI',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Estonia','372','EE/EST',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Ethiopia','251','ET/ETH',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Falkland Islands','500','FK/FLK',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Faroe Islands','298','FO/FRO',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Fiji','679','FJ/FJI',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Finland','358','FI/FIN',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('France','33','FR/FRA',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('French Polynesia','689','PF/PYF',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Gabon','241','GA/GAB',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Gambia','220','GM/GMB',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Georgia','995','GE/GEO',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Germany','49','DE/DEU',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Ghana','233','GH/GHA',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Gibraltar','350','GI/GIB',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Greece','30','GR/GRC',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Greenland','299','GL/GRL',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Grenada','1-473','GD/GRD',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Guam','1-671','GU/GUM',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Guatemala','502','GT/GTM',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Guernsey','44-1481','GG/GGY',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Guinea','224','GN/GIN',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Guinea-Bissau','245','GW/GNB',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Guyana','592','GY/GUY',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Haiti','509','HT/HTI',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Honduras','504','HN/HND',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Hong Kong','852','HK/HKG',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Hungary','36','HU/HUN',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Iceland','354','IS/ISL',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('India','91','IN/IND',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Indonesia','62','ID/IDN',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Iran','98','IR/IRN',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Iraq','964','IQ/IRQ',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Ireland','353','IE/IRL',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Isle of Man','44-1624','IM/IMN',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Israel','972','IL/ISR',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Italy','39','IT/ITA',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Ivory Coast','225','CI/CIV',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Jamaica','1-876','JM/JAM',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Japan','81','JP/JPN',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Jersey','44-1534','JE/JEY',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Jordan','962','JO/JOR',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Kazakhstan','7','KZ/KAZ',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Kenya','254','KE/KEN',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Kiribati','686','KI/KIR',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Kosovo','383','XK/XKX',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Kuwait','965','KW/KWT',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Kyrgyzstan','996','KG/KGZ',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Laos','856','LA/LAO',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Latvia','371','LV/LVA',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Lebanon','961','LB/LBN',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Lesotho','266','LS/LSO',@SouthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Liberia','231','LR/LBR',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Libya','218','LY/LBY',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Liechtenstein','423','LI/LIE',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Lithuania','370','LT/LTU',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Luxembourg','352','LU/LUX',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Macau','853','MO/MAC',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Macedonia','389','MK/MKD',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Madagascar','261','MG/MDG',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Malawi','265','MW/MWI',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Malaysia','60','MY/MYS',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Maldives','960','MV/MDV',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mali','223','ML/MLI',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Malta','356','MT/MLT',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Marshall Islands','692','MH/MHL',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mauritania','222','MR/MRT',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mauritius','230','MU/MUS',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mayotte','262','YT/MYT',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mexico','52','MX/MEX',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Micronesia','691','FM/FSM',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Moldova','373','MD/MDA',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Monaco','377','MC/MCO',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mongolia','976','MN/MNG',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Montenegro','382','ME/MNE',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Montserrat','1-664','MS/MSR',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Morocco','212','MA/MAR',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Mozambique','258','MZ/MOZ',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Myanmar','95','MM/MMR',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Namibia','264','NA/NAM',@SouthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Nauru','674','NR/NRU',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Nepal','977','NP/NPL',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Netherlands','31','NL/NLD',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Netherlands Antilles','599','ANT',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('New Caledonia','687','NC/NCL',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('New Zealand','64','NZ/NZL',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Nicaragua','505','NI/NIC',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Niger','227','NE/NER',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Nigeria','234','NG/NGA',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Niue','683','NU/NIU',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('North Korea','850','KP/PRK',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Northern Mariana Islands','1-670','MP/MNP',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Norway','47','NO/NOR',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Oman','968','OM/OMN',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Pakistan','92','PK/PAK',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Palau','680','PW/PLW',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Palestine','970','PS/PSE',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Panama','507','PA/PAN',@CentralAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Papua New Guinea','675','PG/PNG',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Paraguay','595','PY/PRY',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Peru','51','PE/PER',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Philippines','63','PH/PHL',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Pitcairn','64','PN/PCN',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Poland','48','PL/POL',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Portugal','351','PT/PRT',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Puerto Rico','1-787, 1-939','PR/PRI',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Qatar','974','QA/QAT',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Republic of the Congo','242','CG/COG',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Reunion','262','RE/REU',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Romania','40','RO/ROU',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Russia','7','RU/RUS',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Rwanda','250','RW/RWA',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Barthelemy','590','BL/BLM',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Helena','290','SH/SHN',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Kitts and Nevis','1-869','KN/KNA',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Lucia','1-758','LC/LCA',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Martin','590','MF/MAF',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Pierre and Miquelon','508','PM/SPM',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saint Vincent and the Grenadines','1-784','VC/VCT',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Samoa','685','WS/WSM',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('San Marino','378','SM/SMR',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Sao Tome and Principe','239','ST/STP',@MiddleAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Saudi Arabia','966','SA/SAU',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Senegal','221','SN/SEN',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Serbia','381','RS/SRB',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Seychelles','248','SC/SYC',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Sierra Leone','232','SL/SLE',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Singapore','65','SG/SGP',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Sint Maarten','1-721','SX/SXM',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Slovakia','421','SK/SVK',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Slovenia','386','SI/SVN',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Solomon Islands','677','SB/SLB',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Somalia','252','SO/SOM',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('South Africa','27','ZA/ZAF',@SouthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('South Korea','82','KR/KOR',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('South Sudan','211','SS/SSD',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Spain','34','ES/ESP',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Sri Lanka','94','LK/LKA',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Sudan','249','SD/SDN',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Suriname','597','SR/SUR',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Svalbard and Jan Mayen','47','SJ/SJM',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Eswatini','268','SZ/SWZ',@SouthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Sweden','46','SE/SWE',@EuropeanUnion, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Switzerland','41','CH/CHE',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Syria','963','SY/SYR',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Taiwan','886','TW/TWN',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Tajikistan','992','TJ/TJK',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Tanzania','255','TZ/TZA',@SouthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Thailand','66','TH/THA',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Togo','228','TG/TGO',@WesternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Tokelau','690','TK/TKL',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Tonga','676','TO/TON',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Trinidad and Tobago','1-868','TT/TTO',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Tunisia','216','TN/TUN',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Turkey','90','TR/TUR',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Turkmenistan','993','TM/TKM',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Turks and Caicos Islands','1-649','TC/TCA',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Tuvalu','688','TV/TUV',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('U.S. Virgin Islands','1-340','VI/VIR',@TheCaribbean, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Uganda','256','UG/UGA',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Ukraine','380','UA/UKR',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('United Arab Emirates','971','AE/ARE',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('United Kingdom','44','GB/GBR',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('United States','1','US/USA',@NorthernAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Uruguay','598','UY/URY',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Uzbekistan','998','UZ/UZB',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Vanuatu','678','VU/VUT',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Vatican','379','VA/VAT',@Europe, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Venezuela','58','VE/VEN',@SouthAmerica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Vietnam','84','VN/VNM',@Asia, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Wallis and Futuna','681','WF/WLF',@Oceania, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Western Sahara','212','EH/ESH',@NorthernAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Yemen','967','YE/YEM',@MiddleEast, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Zambia','260','ZM/ZMB',@EasternAfrica, @CreatedBy);
INSERT INTO Country (Name, Code, ISOCode, Region, CreatedBy) VALUES ('Zimbabwe','263','ZW/ZWE',@EasternAfrica, @CreatedBy);
